### ISSUE TITLE
Connection to HiveMQ dropping with an error

### ISSUE THREAD

**Issue by nicholasmparker** [owntracks/talk#179]
Anyone experiencing this?  From the debug logs
2024-03-01 10:47:36.005 E MessageProcessorEndpointMqtt: connectionLost error
 (32109) - java.io.EOFException
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(Unknown Source:213)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:275)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(SourceFile:14)
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(Unknown Source:64)
    ... 1 more

**Comment by jpmens** [comment]
Under the assumption that this error is on our Android app, I'll transfer this issue.
